---

# Apache Maven
- src: "gantsign.maven"


# Atom IDE
- src: "gantsign.atom"


# Facebook Yarn
- src: "ocha.yarn"


# Google Chrome
- src: "cmprescott.chrome"


# HashiCorp Packer
- src: "andrewrothstein.packer"


# HashiCorp Vagrant
- src: "brentwg.vagrant"


# JetBrains IntelliJ IDEA
- src: "gantsign.intellij"


# Microsoft Skype
- src: "mhalano.skypeforlinux"


# NodeJS
- src: "geerlingguy.nodejs"


# OpenJDK
- src: "geerlingguy.java"


# PostgreSQL
- src: "ANXS.postgresql"


# Slack
- src: "wtanaka.slack"


# Vim
- src: "wtanaka.vim"
