---

- hosts:       "localhost"
  become:      true
  become_user: "root"
  roles:
   - role:     "FGtatsuro.virtualbox"
     vars:
      - virtualbox_distributions_with_newpublickey:
         - "zesty"
   - "andrewrothstein.packer"
   - "FGtatsuro.vagrant"
