---

- hosts: "localhost"
  become: true
  become_user: "root"
  roles:
   - "andrewrothstein.packer"
   - "brentwg.vagrant"
   - "cmprescott.chrome"
   - "gantsign.intellij"
   - "gantsign.maven"
   - "geerlingguy.java"
   - "mhalano.skypeforlinux"
   - "ocha.yarn"
   - "wtanaka.slack"
   - "wtanaka.vim"
   - role: "ANXS.postgresql"
     vars:
       - postgresql_version: "10"
   - role: "geerlingguy.nodejs"
     vars:
      - nodejs_version: "8.x"
   - role: "gantsign.atom"
     users:
      - username: "{{ansible_env.SUDO_USER}}"
        atom_packages:
         - "atom-beautify"
         - "atom-html-preview"
         - "atom-ide-ui"
         - "autocomplete-modules"
         - "busy-signal"
         - "docblockr"
         - "file-icons"
         - "git-plus"
         - "highlight-selected"
         - "ide-css"
         - "ide-html"
         - "ide-json"
         - "ide-typescript"
         - "ide-vue"
         - "ide-yaml"
         - "language-vue"
         - "minimap"
         - "project-manager"
         - "sonarlint"


